name: Upload to R2

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.7

      - name: Sync content directory to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL: https://a41d50ecaf0ae0f86dd1824ef6729cb2.r2.cloudflarestorage.com
          AWS_DEFAULT_REGION: auto
        run: |
          aws s3 sync content/ s3://kcd-rag/content/ \
            --endpoint-url $AWS_ENDPOINT_URL \
            --size-only --delete
